language: cpp
dist: bionic
matrix:
  include:
  - name: Linux
    addons:
      apt_packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libxmp-dev
    script:
    - make
    deploy:
      provider: "releases"
      api_key:
        secure: "..."
      skip_cleanup: true
      on:
        branch: master
