language: cpp
dist: bionic
matrix:
  include:
  - name: Linux
    addons:
      apt_packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libxmp-dev
    script:
    - make
    deploy:
      provider: releases
      github-token: $GITHUB_ACCESS_TOKEN
      file_glob: true
      file: directory/*
      skip_cleanup: true
      overwrite: true
      on:
        branch: master
