name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt-get
      run: sudo apt-get update && sudo apt-get install cmake libsdl2-dev libsdl2-mixer-dev libxmp-dev
    - name: build
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../install && cmake --build . --target install

